'use strict';
const gTTS = require('gtts');

var gtts = new gTTS("A simple message generated by Google's TTS for CEIS312");
        
gtts.save('voice.mp3', function (err, result) {
    if (err) { throw new Error(err); }
       
});
